# AI News Sources — dev tools + research focus

rss_feeds:
  # Lab blogs — model releases, research, APIs
  - name: "OpenAI Blog"
    url: "https://openai.com/blog/rss.xml"
    priority: high

  - name: "Anthropic News"
    url: "https://www.anthropic.com/news/rss.xml"
    priority: high

  - name: "Google DeepMind"
    url: "https://www.deepmind.com/blog/rss.xml"
    priority: high

  - name: "Google Research"
    url: "https://research.google/blog/rss/"
    priority: high

  # Community & practitioner voices
  - name: "Latent Space"
    url: "https://www.latent.space/feed"
    priority: high

  - name: "HuggingFace Blog"
    url: "https://huggingface.co/blog/feed.xml"
    priority: high

  - name: "Import AI"
    url: "https://importai.substack.com/feed"
    priority: high

  - name: "One Useful Thing"
    url: "https://oneusefulthing.substack.com/feed"
    priority: high

  # Tools & infra
  - name: "NVIDIA Developer Blog"
    url: "https://blogs.nvidia.com/feed/"
    priority: medium

  - name: "Simon Willison"
    url: "https://simonwillison.net/atom/everything/"
    priority: medium

  - name: "Ben's Bites"
    url: "https://bens.substack.com/feed"
    priority: medium

# Filtering
keywords_boost:
  - "model"
  - "release"
  - "paper"
  - "benchmark"
  - "open source"
  - "API"
  - "tool"
  - "framework"
  - "agent"
  - "launch"
  - "research"
  - "training"
  - "inference"

keywords_skip:
  - "sponsored"
  - "advertisement"
  - "regulation"
  - "policy"
  - "lawsuit"
  - "funding round"
  - "acquisition"
