# AI News Sources — trending signals + lab blogs + practitioner voices

rss_feeds:
  # 🔥 Trending / community-ranked (highest signal)
  - name: "Hacker News AI"
    url: "https://hnrss.org/newest?q=AI+OR+LLM+OR+Claude+OR+GPT+OR+agent+OR+model&points=100"
    priority: high

  - name: "Hacker News Frontpage"
    url: "https://hnrss.org/frontpage?q=AI+OR+LLM+OR+model+OR+open+source&points=50"
    priority: high

  # Lab blogs — model releases, research, APIs
  - name: "OpenAI Blog"
    url: "https://openai.com/blog/rss.xml"
    priority: high

  - name: "Anthropic News"
    url: "https://www.anthropic.com/news/rss.xml"
    priority: high

  - name: "Google DeepMind"
    url: "https://www.deepmind.com/blog/rss.xml"
    priority: high

  # Practitioner voices
  - name: "Latent Space"
    url: "https://www.latent.space/feed"
    priority: high

  - name: "HuggingFace Blog"
    url: "https://huggingface.co/blog/feed.xml"
    priority: high

  - name: "Simon Willison"
    url: "https://simonwillison.net/atom/everything/"
    priority: high

  - name: "Ahead of AI"
    url: "https://magazine.sebastianraschka.com/feed"
    priority: high
    hours_back: 168  # weekly newsletter — look back 7 days

  - name: "The Gradient"
    url: "https://thegradient.pub/rss/"
    priority: high
    hours_back: 168

  - name: "Import AI"
    url: "https://importai.substack.com/feed"
    priority: medium
    hours_back: 168

  - name: "One Useful Thing"
    url: "https://oneusefulthing.substack.com/feed"
    priority: medium
    hours_back: 168

  - name: "Ben's Bites"
    url: "https://bens.substack.com/feed"
    priority: medium
    hours_back: 168

  - name: "NVIDIA Developer Blog"
    url: "https://blogs.nvidia.com/feed/"
    priority: medium

  - name: "Elvis Saravia (DAIR.AI)"
    url: "https://elvissaravia.substack.com/feed"
    priority: medium
    hours_back: 168

# Filtering
keywords_boost:
  - "model"
  - "release"
  - "open source"
  - "API"
  - "agent"
  - "launch"
  - "paper"
  - "benchmark"
  - "tool"
  - "framework"
  - "trending"
  - "viral"

keywords_skip:
  - "sponsored"
  - "advertisement"
  - "lawsuit"
  - "funding round"
  - "acquisition"
  - "IPO"
